### PR TITLE
remove qs take 2

### LINKED ISSUE #77: Remove `qs` as dependency of this library
It doesn't add much value, we could roll out our own helper and `qs` has other dependencies we don't want to be bundling with domain-functions.

### PR DESCRIPTION
**Pull request by diogob**
Another attempt at #84, it should also close #77.

Just trying a different approach for fun.

The previous attempt would still fail in some of the new test cases introduced here.

### CODE REVIEW

**Comment by diogob** [comment]
@danielweinmann please take a look at the test cases. Since this is going to be a breaking change let's ensure we cover all cases we care about.

**Review by gustavoguichard — APPROVED** [review]

**Comment by gustavoguichard** [comment]
@diogob I changed the base branch for this PR from `main` to `v2`

**Comment by gustavoguichard** [comment]
@diogob , let's get this merged? Can't stand qs anymore:
https://bundlephobia.com/package/domain-functions@1.8.0

**Review by danielweinmann — CHANGES_REQUESTED** [review]
@gustavoguichard, I asked @diogob for a few extra test cases to make sure we're dealing correctly with deeply nested objects/arrays.

**Comment by diogob** [comment]
@danielweinmann @gustavoguichard I have rebased `v2` and this branch on top of the new `v2`.
I have also added a fancy new test case to cover several cases in the same call.

**Review by danielweinmann — APPROVED** [review]

**Pull request merged**
